version: '3'

services:
    brevetsapp:
        build: ./brevetsapp
        command: python -u flask_brevets.py 
        volumes:
            - ./brevetsapp:/stuff
        ports:
            - "5002:5000"
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb
            
    restapi:
        build: ./api
        volumes:
            - ./api:/stuff
        ports:
            - 5001:5000
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb
            
    website:
        build: ./website
        volumes:
            - ./website:/stuff
        command: python -u api_display.py 
        ports:
            - "5000:5000"
        depends_on:
            - restapi
            - ourdb
        environment:
            BACKEND_ADDR: restapi
            BACKEND_PORT: 5000
            MONGODB_HOSTNAME: ourdb
          
    ourdb:
        image: mongo:latest
